# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 25f4914d6333b75bd5a47c4e2f4c813ea75f6d5fc28c9ce953f43190af920e677e1e6c14c8f843e82282f598fab0a5449a3e8edc1f11e6151c3e4136fa71d3ab

test:
  secret_key_base: 70de659f17f10ff50ae56104055b805d2ea53bf4ac4bde565d3c3b1e39f377fe0732b0f2bf2c89647f8ef9830c9d20619fa086c7263a0f0a02d53f3ae09ae314

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
